version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: logistics_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/data/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
